[package]
name = "wow_version_switcher"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
arboard = { version = "3.5.0" }
clap = { version = "4.5.37", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
shellexpand = "3.1.1"
toml = "0.8.22"
