name: Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      release:
        description: 'Create a draft release'
        type: boolean
        required: false
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: wow_version_switcher-linux
            asset_name: wow_version_switcher-linux
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: wow_version_switcher-windows
            asset_name: wow_version_switcher-windows.exe

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Build
      working-directory: ./wow_version_switcher
      run: cargo build --release --target ${{ matrix.target }}

    - name: Copy binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: cp ./wow_version_switcher/target/${{ matrix.target }}/release/wow_version_switcher ./${{ matrix.artifact_name }}

    - name: Copy binary (Windows)
      if: matrix.os == 'windows-latest'
      run: copy .\wow_version_switcher\target\${{ matrix.target }}\release\wow_version_switcher.exe .\${{ matrix.asset_name }}
      shell: cmd

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ./${{ matrix.os == 'windows-latest' && matrix.asset_name || matrix.artifact_name }}
        if-no-files-found: error
        retention-days: 3

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.release == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ steps.date.outputs.date }}-${{ github.run_number }}
          name: Release ${{ steps.date.outputs.date }}
          draft: true
          files: |
            wow_version_switcher-linux/wow_version_switcher-linux
            wow_version_switcher-windows/wow_version_switcher-windows.exe